//! 将应用快捷键序列化为 XDG GlobalShortcuts preferred trigger。

use crate::config::KeyboardShortcut;

pub(in crate::shortcut) fn portal_trigger(shortcut: KeyboardShortcut) -> Result<String, String> {
    use keyboard_types::Modifiers;

    let modifiers = shortcut.modifiers();
    let mut preferred = Vec::with_capacity(5);
    for (modifier, portal) in [
        (Modifiers::CONTROL, "CTRL"),
        (Modifiers::ALT, "ALT"),
        (Modifiers::SHIFT, "SHIFT"),
        (Modifiers::SUPER, "LOGO"),
    ] {
        if modifiers.contains(modifier) {
            preferred.push(portal);
        }
    }
    let key = portal_key_name(shortcut.key())
        .ok_or_else(|| format!("快捷键无法转换为 XDG trigger：{}", shortcut.id()))?;
    preferred.push(key);
    Ok(preferred.join("+"))
}

fn portal_key_name(code: keyboard_types::Code) -> Option<&'static str> {
    let code = code.to_string();
    Some(match code.as_str() {
        "KeyA" => "a",
        "KeyB" => "b",
        "KeyC" => "c",
        "KeyD" => "d",
        "KeyE" => "e",
        "KeyF" => "f",
        "KeyG" => "g",
        "KeyH" => "h",
        "KeyI" => "i",
        "KeyJ" => "j",
        "KeyK" => "k",
        "KeyL" => "l",
        "KeyM" => "m",
        "KeyN" => "n",
        "KeyO" => "o",
        "KeyP" => "p",
        "KeyQ" => "q",
        "KeyR" => "r",
        "KeyS" => "s",
        "KeyT" => "t",
        "KeyU" => "u",
        "KeyV" => "v",
        "KeyW" => "w",
        "KeyX" => "x",
        "KeyY" => "y",
        "KeyZ" => "z",
        "Digit0" => "0",
        "Digit1" => "1",
        "Digit2" => "2",
        "Digit3" => "3",
        "Digit4" => "4",
        "Digit5" => "5",
        "Digit6" => "6",
        "Digit7" => "7",
        "Digit8" => "8",
        "Digit9" => "9",
        "Backquote" => "grave",
        "Backslash" => "backslash",
        "BracketLeft" => "bracketleft",
        "BracketRight" => "bracketright",
        "Comma" => "comma",
        "Equal" => "equal",
        "Minus" => "minus",
        "Period" => "period",
        "Quote" => "apostrophe",
        "Semicolon" => "semicolon",
        "Slash" => "slash",
        "Backspace" => "BackSpace",
        "CapsLock" => "Caps_Lock",
        "Enter" => "Return",
        "Space" => "space",
        "Tab" => "Tab",
        "Delete" => "Delete",
        "End" => "End",
        "Home" => "Home",
        "Insert" => "Insert",
        "PageDown" => "Page_Down",
        "PageUp" => "Page_Up",
        "ArrowDown" => "Down",
        "ArrowLeft" => "Left",
        "ArrowRight" => "Right",
        "ArrowUp" => "Up",
        "PrintScreen" => "Print",
        "ScrollLock" => "Scroll_Lock",
        "Pause" => "Pause",
        "Numpad0" => "KP_0",
        "Numpad1" => "KP_1",
        "Numpad2" => "KP_2",
        "Numpad3" => "KP_3",
        "Numpad4" => "KP_4",
        "Numpad5" => "KP_5",
        "Numpad6" => "KP_6",
        "Numpad7" => "KP_7",
        "Numpad8" => "KP_8",
        "Numpad9" => "KP_9",
        "NumpadAdd" => "KP_Add",
        "NumpadDecimal" => "KP_Decimal",
        "NumpadDivide" => "KP_Divide",
        "NumpadMultiply" => "KP_Multiply",
        "NumpadSubtract" => "KP_Subtract",
        "F1" => "F1",
        "F2" => "F2",
        "F3" => "F3",
        "F4" => "F4",
        "F5" => "F5",
        "F6" => "F6",
        "F7" => "F7",
        "F8" => "F8",
        "F9" => "F9",
        "F10" => "F10",
        "F11" => "F11",
        "F12" => "F12",
        "F13" => "F13",
        "F14" => "F14",
        "F15" => "F15",
        "F16" => "F16",
        "F17" => "F17",
        "F18" => "F18",
        "F19" => "F19",
        "F20" => "F20",
        "F21" => "F21",
        "F22" => "F22",
        "F23" => "F23",
        "F24" => "F24",
        _ => return None,
    })
}
