[package]
name = "lunamate-config"
version.workspace = true
edition.workspace = true

[lints.clippy]
unwrap_used = "deny"

[dependencies]
arc-swap.workspace = true
global-hotkey.workspace = true
gpui-component.workspace = true
log.workspace = true
lunamate-agent.workspace = true
parking_lot.workspace = true
rust-i18n.workspace = true
tokio.workspace = true
toml_edit.workspace = true

[dev-dependencies]
tempfile = "3.27.0"
